"""p12_C_offline_sample.py -- Track C / C4 (real), C5, C6, C9, C10 on an offline sample of run 20260911_115904 families.

Production path driven (no re-implementation of the valuation loop):
  CanonicalDOIObservationBridge.resolve -> ThesisConditionedContractFamilyGenerator.generate
  -> DeterministicContractValuationService.evaluate_family  (canonical_data/dynamic_options_valuation.py:260-470)
The service persists observations/assessments to SQLite, so it is pointed at a NEW scratch registry under
probes/_scratch_c6/ (never data/, never the db_copies). The scratch registry is seeded only with the run_registry
row and the dataset_registry rows of the sampled tickers, copied from db_copies/control_plane.sqlite (read-only).
Canonical chain payloads are read (read-only, sha256-verified by the bridge) from data/canonical/.

Inputs per family: doi_contract_families row (thesis: origin spot, target, invalidation, hold, cutoff) of run
20260911_115904; rate = load_market_rate(macro_snapshot.json) (C1: 0.0395 MACRO:T3M); dividend = options CSV
ev3_dividend_yield_used (as production L290); governed constants = config/governed_constants_v1.json.
Forecast vol:
  pass AS_WIRED  -> exactly as production L311-314: options CSV l3_forward_realised_vol / forecast_vol_annual_fraction /
                   forward_realised_vol (none of these columns exist in the CSV -> None).
  pass GARCH_SUB -> garch_forecast_vol from the governed final book (TESTER SUBSTITUTION, same as C2 probe).
Provider finality gate (production L258) is bypassed: the sampled families were already generated by the run, which
means they passed it.

Usage: python p12_C_offline_sample.py [n_call n_put n_as_wired]
Outputs (beside this script): p12_C_offline_assessments.csv (one row per family, GARCH_SUB),
p12_C_offline_assessments_all_contracts.csv (every assessed contract, both passes), p12_C_offline_sample.out.json
"""
from __future__ import annotations
import json, math, random, sqlite3, sys, time
from datetime import datetime, timezone
from pathlib import Path
import pandas as pd

ROOT = Path(r"C:\Users\ACKVerissimo\AVSHUNTER-Intelligence")
sys.path.insert(0, str(ROOT))
from canonical_data.dynamic_options_bridge import CanonicalDOIObservationBridge  # noqa: E402
from canonical_data.dynamic_options_family import ThesisConditionedContractFamilyGenerator  # noqa: E402
from canonical_data.dynamic_options_valuation import DeterministicContractValuationService  # noqa: E402
from canonical_data.option_liquidity_lifecycle import OptionLiquidityLifecycleStore, ThesisState, MonitorState  # noqa: E402
from canonical_data.registry import CanonicalRegistry  # noqa: E402
from canonical_data.market_rate_observation import load_market_rate  # noqa: E402
from domain.dynamic_options_intelligence import OptionObservationKind, UnderlyingThesisRef  # noqa: E402

RUN = "20260911_115904"
RD = ROOT / "data/output/runs" / RUN
HERE = Path(__file__).resolve().parent
SCR = HERE / "_scratch_c6"
SCR.mkdir(exist_ok=True)
SRC_DB = ROOT / "audit/td/AVS-TD-001/db_copies/control_plane.sqlite"
SEED = 20260913
n_call, n_put, n_wired = (int(x) for x in (sys.argv[1:4] if len(sys.argv) >= 4 else (120, 80, 25)))

t0 = time.time()
out: dict = {"run": RUN, "seed": SEED, "n_call_requested": n_call, "n_put_requested": n_put, "n_as_wired": n_wired}

# ---------------- sample from contracts_tested jsonl ----------------
jl = []
with open(RD / "options" / f"contracts_tested_{RUN}.jsonl", encoding="utf-8") as fh:
    for line in fh:
        d = json.loads(line)
        jl.append({"ticker": d["ticker"], "direction": d["direction"], "selected_contract_symbol": d.get("selected_contract_symbol") or ""})
jdf = pd.DataFrame(jl)
out["jsonl_families"] = len(jdf); out["jsonl_direction_counts"] = jdf["direction"].value_counts().to_dict()
src = sqlite3.connect(f"file:{SRC_DB.as_posix()}?mode=ro", uri=True)
src.row_factory = sqlite3.Row
fam = pd.read_sql_query("select * from doi_contract_families where run_id=?", src, params=(RUN,))
jdf = jdf.merge(fam[["ticker", "governed_direction"]].rename(columns={"governed_direction": "direction"}), on=["ticker", "direction"])
rng = random.Random(SEED)
calls = sorted(jdf.loc[jdf.direction == "CALL", "ticker"]); puts = sorted(jdf.loc[jdf.direction == "PUT", "ticker"])
sample = rng.sample(calls, min(n_call, len(calls))) + rng.sample(puts, min(n_put, len(puts)))
out["sampled_tickers"] = len(sample)

opt = pd.read_csv(RD / "options" / f"options_intelligence_{RUN}.csv", low_memory=False,
                  usecols=lambda c: c in {"ticker", "ev3_dividend_yield_used", "l3_forward_realised_vol",
                                          "forecast_vol_annual_fraction", "forward_realised_vol"})
opt["ticker"] = opt["ticker"].astype(str).str.strip().str.upper()
opt = opt.drop_duplicates("ticker").set_index("ticker")
out["options_csv_forecast_vol_columns_present"] = [c for c in ("l3_forward_realised_vol", "forecast_vol_annual_fraction", "forward_realised_vol") if c in opt.columns]
fb = pd.read_csv(RD / "intelligence_lab" / f"final_opportunity_book_{RUN}.csv", low_memory=False,
                 usecols=["ticker", "garch_forecast_vol", "monetisability_state", "convexity_score"])
fb["ticker"] = fb["ticker"].astype(str).str.upper()
fb = fb.drop_duplicates("ticker").set_index("ticker")
constants = json.loads((ROOT / "config/governed_constants_v1.json").read_text(encoding="utf-8-sig"))
rate_obs = load_market_rate(RD / "macro_snapshot.json")
out["rate"] = rate_obs.to_dict()
FLOOR = float(constants["contract_economics"]["profit_floor"])


def num(v):
    try:
        f = float(v)
        return f if math.isfinite(f) else None
    except (TypeError, ValueError):
        return None


def build_store(tag: str, tickers: list[str]) -> tuple[Path, OptionLiquidityLifecycleStore]:
    path = SCR / f"control_plane_scratch_{tag}.sqlite"
    for suffix in ("", "-wal", "-shm"):
        p = Path(str(path) + suffix)
        if p.exists():
            p.unlink()
    store = OptionLiquidityLifecycleStore(CanonicalRegistry(path))
    store.initialise()
    dst = sqlite3.connect(path)
    for table, where, params in (("run_registry", "run_id=?", (RUN,)),):
        rows = src.execute(f"select * from {table} where {where}", params).fetchall()
        for r in rows:
            cols = r.keys()
            dst.execute(f"insert or ignore into {table} ({','.join(cols)}) values ({','.join('?' * len(cols))})", tuple(r))
    ds_ids = set()
    for t in tickers:
        row = fam.loc[fam.ticker == t].iloc[0]
        ds_ids.update(json.loads(row["source_dataset_ids_json"]))
    dcols = [c[1] for c in dst.execute("pragma table_info(dataset_registry)")]
    for dsid in ds_ids:
        r = src.execute("select * from dataset_registry where dataset_id=?", (dsid,)).fetchone()
        if r is None:
            continue
        cols = [c for c in r.keys() if c in dcols]
        run_id = r["source_run_id"]
        if run_id and run_id != RUN:  # FK on source_run_id -> copy that run_registry row too
            rr = src.execute("select * from run_registry where run_id=?", (run_id,)).fetchone()
            if rr is not None:
                dst.execute(f"insert or ignore into run_registry ({','.join(rr.keys())}) values ({','.join('?' * len(rr.keys()))})", tuple(rr))
        dst.execute(f"insert or ignore into dataset_registry ({','.join(cols)}) values ({','.join('?' * len(cols))})", tuple(r[c] for c in cols))
    dst.commit(); dst.close()
    return path, store


PATHS = ["FLAT", "FAVOURABLE_1SIGMA", "FAVOURABLE_2SIGMA", "REACHABLE", "STRUCTURAL_DISCLOSURE", "ADVERSE_INVALIDATION"]
TIMINGS = ["EARLY", "MID", "LATE"]; STRESS = ["CONTRACTED", "BASE", "EXPANDED"]


def run_pass(tag: str, tickers: list[str], vol_mode: str) -> tuple[list[dict], list[dict], list[dict]]:
    path, store = build_store(tag, tickers)
    bridge = CanonicalDOIObservationBridge(registry_path=path)
    gen = ThesisConditionedContractFamilyGenerator(store)
    contracts, exceptions, taxonomy_runway = [], [], []
    for t in tickers:
        fr = fam.loc[fam.ticker == t].iloc[0]
        try:
            cutoff = pd.to_datetime(fr["evidence_cutoff_utc"], utc=True).to_pydatetime()
            direction = fr["governed_direction"]
            spot = float(fr["origin_spot"])
            target = num(fr["target_spot"]); inval = num(fr["invalidation_spot"])
            thesis = UnderlyingThesisRef(
                thesis_id=fr["thesis_id"], thesis_version=int(fr["thesis_version"]), ticker=t,
                governed_direction=direction, origin_spot=spot,
                origin_timestamp_utc=pd.to_datetime(fr["origin_timestamp_utc"], utc=True).to_pydatetime(),
                target_spot=target, invalidation_spot=inval, planned_hold_sessions=int(fr["planned_hold_sessions"]),
                planned_hold_source=fr["planned_hold_source"], evidence_cutoff_utc=cutoff)
            if store.latest_thesis(thesis.thesis_id) is None:
                store.record_thesis_event(
                    thesis_id=thesis.thesis_id, event_key=f"DOI_COMPLETED_SESSION:{cutoff.date().isoformat()}",
                    run_id=RUN, ticker=t, direction=direction, thesis_state=ThesisState.ACTIVE,
                    monitor_state=MonitorState.ACTIVE, reason_code="GOVERNED_PIPELINE_THESIS",
                    structural_target=target, invalidation_spot=inval, recorded_at=cutoff,
                    metadata={"source": "p12_C_offline_sample", "authority": "ADVISORY_ONLY"},
                    calculation_version="doi-production-integration-v1")
            obs = bridge.resolve(ticker=t, session_date=cutoff.date(), observation_kind=OptionObservationKind.COMPLETED_SESSION,
                                 evidence_cutoff_utc=cutoff, acquire_missing=None)
            if obs.physical_fetch_count:
                raise RuntimeError("UNEXPECTED_PROVIDER_FETCH")
            generated = gen.generate(thesis=thesis, observation=obs, run_id=RUN, current_spot=spot, evaluation_cutoff_utc=cutoff)
            regenerated_match = generated.family.family_id == fr["family_id"]
            if not obs.available or not generated.family.candidate_symbols:
                exceptions.append({"ticker": t, "reason": "FAMILY_DATA_INSUFFICIENT"}); continue
            div_raw = num(opt["ev3_dividend_yield_used"].get(t)) if t in opt.index else None
            div_ok = div_raw is not None and div_raw >= 0
            if vol_mode == "AS_WIRED":
                fv = None
                for c in ("l3_forward_realised_vol", "forecast_vol_annual_fraction", "forward_realised_vol"):
                    if c in opt.columns and t in opt.index and num(opt[c].get(t)) is not None:
                        fv = num(opt[c].get(t)); break
            else:
                fv = num(fb["garch_forecast_vol"].get(t)) if t in fb.index else None
            svc = DeterministicContractValuationService(
                store, risk_free_rate=rate_obs.rate_annual_fraction, dividend_yield=max(0.0, div_raw or 0.0),
                dividend_yield_available=div_ok, market_rate_observation=rate_obs, governed_constants=constants)
            res = svc.evaluate_family(generated_family=generated, observation=obs, contract_symbols=generated.display_symbols,
                                      annual_forecast_vol=fv)
            frame = obs.frame.copy()
            sym_col = next(c for c in ("symbol", "option_symbol", "contract_symbol") if c in frame.columns)
            frame = frame.set_index(frame[sym_col].astype(str).str.replace(" ", ""))
            for item in res.results:
                md = item.assessment.metadata
                e2 = md["contract_assessment_v2"]; ra = md["reachability_assessment_v1"]; vb = md["volatility_budget_v2"]
                sym = item.assessment.contract_symbol
                q = frame.loc[sym] if sym in frame.index else None
                if isinstance(q, pd.DataFrame):
                    q = q.iloc[0]
                grid = {s["scenario_id"]: s for s in e2["scenarios"]}
                row = {
                    "pass": vol_mode, "family_id": item.assessment.family_id, "family_id_regenerated_matches_stored": regenerated_match,
                    "ticker": t, "direction": direction, "contract_symbol": sym,
                    "selected_by_legacy_jsonl": sym == jdf.loc[jdf.ticker == t, "selected_contract_symbol"].iloc[0],
                    "strike": None, "expiry": None,
                    "bid": None if q is None else num(q.get("bid")), "ask": None if q is None else num(q.get("ask")),
                    "iv": None if q is None else num(next((q.get(c) for c in ("iv", "implied_vol", "implied_volatility") if c in q.index), None)),
                    "spot": spot, "hold_sessions": int(fr["planned_hold_sessions"]), "evidence_cutoff_utc": cutoff.isoformat(),
                    "risk_free_rate": md["risk_free_rate"], "rate_source": (md.get("market_rate_observation") or {}).get("rate_source"),
                    "rate_as_of": (md.get("market_rate_observation") or {}).get("rate_as_of"),
                    "dividend_yield": md["dividend_yield"], "dividend_yield_available": md["dividend_yield_available"],
                    "annual_forecast_vol": fv, "expected_move_hold_fraction": vb.get("expected_move_fraction"),
                    "reachable_target_spot": ra.get("reachable_target_spot"), "reach_ratio": ra.get("reach_ratio"),
                    "reach_quality_state": ra.get("quality_state"), "validation_state": ra.get("validation_state"),
                    "bias_multiplier_applied": ra.get("bias_multiplier_applied"),
                    "budget_validation_state": vb.get("validation_state"),
                    "structural_target": target, "invalidation": inval,
                    "v1_applicability_state": str(item.valuation.applicability_state.value),
                    "utility_v1": item.valuation.ranking_score_uncalibrated,
                    "utility_v2": e2["deterministic_utility"],
                    "assessment_ranking_score_uncalibrated": item.assessment.ranking_score_uncalibrated,
                    "applicability": e2["applicability"], "applicability_reason": e2["applicability_reason"],
                    "monetisability_state": e2["monetisability_state"], "monetisability_reason": e2["monetisability_reason"],
                    "convexity_score": e2["convexity_score"], "convexity_label": e2["convexity_label"],
                    "spread_fraction_mid": e2["spread_fraction_mid"], "friction_version": e2["friction_version"],
                    "calendar_version": e2["calendar_version"], "basis": e2["basis"],
                    "profit_floor_applied": e2["profit_floor_applied"],
                    "economics_carries_validation_state": any(k in e2 for k in ("validation_state", "bias_multiplier_applied")),
                    "legacy_book_monetisability_state": fb["monetisability_state"].get(t) if t in fb.index else None,
                    "legacy_book_convexity_score": fb["convexity_score"].get(t) if t in fb.index else None,
                }
                from canonical_data.option_identity import parse_occ_symbol
                ident = parse_occ_symbol(sym)
                row["strike"] = ident.strike; row["expiry"] = ident.expiry.isoformat()
                for p in PATHS:
                    for tm in TIMINGS:
                        for st in STRESS:
                            s = grid.get(f"{p}:{tm}:{st}")
                            row[f"net:{p}:{tm}:{st}"] = None if s is None else s["net_return_fraction"]
                            row[f"theo:{p}:{tm}:{st}"] = None if s is None else s["theoretical_value_per_share"]
                s = grid.get("REACHABLE:LATE:BASE")
                if s is None:
                    row["tester_state"] = None
                else:
                    h = s["net_return_fraction"]
                    row["tester_state"] = ("SCENARIO_MONETISABLE" if h >= FLOOR else "SCENARIO_LIMITED" if h > 0 else "NOT_CURRENTLY_MONETISABLE")
                row["tester_state_matches"] = (row["tester_state"] == row["monetisability_state"]) if row["tester_state"] else None
                contracts.append(row)
            # contracts expiring inside the hold (structurally excluded by the generator, never valued)
            tax = generated.family.metadata.get("complete_candidate_taxonomy", []) if hasattr(generated.family, "metadata") else []
            for a in tax:
                if "INSUFFICIENT_SESSION_RUNWAY" in (a.get("structural_exclusions") or []) and a.get("option_side") == direction:
                    taxonomy_runway.append({"ticker": t, "direction": direction, "contract_symbol": a.get("contract_symbol"),
                                            "expiry": a.get("expiry"), "remaining_sessions": a.get("remaining_sessions"),
                                            "required_sessions": a.get("required_sessions"), "hold": int(fr["planned_hold_sessions"]),
                                            "bid": a.get("bid"), "ask": a.get("ask"), "strike": a.get("strike"),
                                            "state": a.get("state"), "in_display": a.get("contract_symbol") in generated.display_symbols})
        except Exception as err:  # retain per-ticker exception
            exceptions.append({"ticker": t, "reason": f"{type(err).__name__}: {str(err)[:200]}"})
    return contracts, exceptions, taxonomy_runway


garch, garch_exc, runway = run_pass("garch_sub", sample, "GARCH_SUB")
out["garch_sub_exceptions"] = garch_exc
wired_tickers = sample[: n_wired // 2] + sample[n_call: n_call + (n_wired - n_wired // 2)]
wired, wired_exc, _ = run_pass("as_wired", wired_tickers, "AS_WIRED")
out["as_wired_exceptions"] = wired_exc
allc = pd.DataFrame(garch + wired)
allc.to_csv(HERE / "p12_C_offline_assessments_all_contracts.csv", index=False)
pd.DataFrame(runway).to_csv(HERE / "p12_C_offline_runway_excluded.csv", index=False)
out["elapsed_s_after_valuation"] = round(time.time() - t0, 1)

# ---------------- one row per family (GARCH_SUB): legacy-selected contract if valued, else max utility_v2, else max v1 ----
g = allc.loc[allc["pass"] == "GARCH_SUB"].copy()
rows = []
for fid, grp in g.groupby("family_id", sort=False):
    pick = grp.loc[grp["selected_by_legacy_jsonl"]]
    rule = "LEGACY_SELECTED_CONTRACT"
    if pick.empty:
        v2 = grp.dropna(subset=["utility_v2"])
        if not v2.empty:
            pick = v2.loc[[v2["utility_v2"].idxmax()]]; rule = "MAX_UTILITY_V2_IN_DISPLAY_SET"
        else:
            v1 = grp.dropna(subset=["utility_v1"])
            pick = (v1.loc[[v1["utility_v1"].idxmax()]] if not v1.empty else grp.iloc[[0]]); rule = "MAX_UTILITY_V1_OR_FIRST"
    r = pick.iloc[0].to_dict(); r["contract_pick_rule"] = rule; r["family_contracts_assessed"] = len(grp)
    rows.append(r)
fam_df = pd.DataFrame(rows)
lead = ["family_id", "ticker", "direction", "contract_symbol", "contract_pick_rule", "strike", "expiry", "bid", "ask", "iv", "spot",
        "hold_sessions", "reachable_target_spot", "structural_target", "invalidation"]
fam_df = fam_df[lead + [c for c in fam_df.columns if c not in lead]]
fam_df.to_csv(HERE / "p12_C_offline_assessments.csv", index=False)


def dist(df, col):
    return {d: df.loc[df.direction == d, col].value_counts(dropna=False).to_dict() for d in ("CALL", "PUT")}


def spearman(df):
    x = df.dropna(subset=["utility_v1", "utility_v2"])
    res = {}
    for d in ("CALL", "PUT", "ALL"):
        s = x if d == "ALL" else x.loc[x.direction == d]
        res[d] = {"n": len(s), "rho": None if len(s) < 3 else float(s["utility_v1"].rank().corr(s["utility_v2"].rank()))}
    return res


def within_family_spearman(df):
    rhos = []
    for _, grp in df.dropna(subset=["utility_v1", "utility_v2"]).groupby("family_id"):
        if len(grp) >= 3 and grp["utility_v1"].nunique() > 1 and grp["utility_v2"].nunique() > 1:
            rhos.append(float(grp["utility_v1"].rank().corr(grp["utility_v2"].rank())))
    s = pd.Series(rhos, dtype=float)
    top_same = 0; top_n = 0
    for _, grp in df.dropna(subset=["utility_v1", "utility_v2"]).groupby("family_id"):
        if len(grp) >= 2:
            top_n += 1; top_same += int(grp["utility_v1"].idxmax() == grp["utility_v2"].idxmax())
    return {"families": len(s), "median_rho": None if s.empty else float(s.median()),
            "iqr": None if s.empty else [float(s.quantile(.25)), float(s.quantile(.75))],
            "share_rho_below_0_7": None if s.empty else float((s < 0.7).mean()),
            "top_contract_same_v1_v2": top_same, "families_with_2plus": top_n}


w = allc.loc[allc["pass"] == "AS_WIRED"]
out["as_wired"] = {"families": w["family_id"].nunique(), "contracts": len(w),
                   "applicability": w["applicability"].value_counts().to_dict(),
                   "monetisability_state": w["monetisability_state"].value_counts().to_dict(),
                   "utility_v2_non_null": int(w["utility_v2"].notna().sum()),
                   "utility_v1_non_null": int(w["utility_v1"].notna().sum()),
                   "assessment_ranking_score_equals_v1_where_v2_null": int(((w["utility_v2"].isna()) & (w["assessment_ranking_score_uncalibrated"] == w["utility_v1"])).sum()),
                   "reach_quality_state": w["reach_quality_state"].value_counts(dropna=False).to_dict()}
out["garch_sub_contracts"] = {
    "families_valued": int(g["family_id"].nunique()), "contracts": len(g),
    "family_id_regenerated_matches_stored": g.drop_duplicates("family_id")["family_id_regenerated_matches_stored"].value_counts().to_dict(),
    "applicability_by_dir": dist(g, "applicability"), "monetisability_by_dir": dist(g, "monetisability_state"),
    "monetisability_reason_by_dir": dist(g, "monetisability_reason"),
    "tester_state_matches": g["tester_state_matches"].value_counts(dropna=False).to_dict(),
    "convexity_label_by_dir": dist(g, "convexity_label"),
    "convexity_distinct": int(g["convexity_score"].round(10).nunique()),
    "convexity_eq_2_0": int((g["convexity_score"] == 2.0).sum()),
    "rate_lineage_present": int((g["rate_source"].notna() & g["rate_as_of"].notna() & g["risk_free_rate"].notna()).sum()),
    "friction_calendar_basis_present": int((g["friction_version"].eq("friction_model_v1") & g["calendar_version"].eq("XNYS_BRIDGE_V1") & g["basis"].eq("AT_GOVERNED_TIME_STOP")).sum()),
    "validation_state_by_dir": dist(g, "validation_state"), "reach_quality_by_dir": dist(g, "reach_quality_state"),
    "bias_multiplier_applied": g["bias_multiplier_applied"].value_counts(dropna=False).to_dict(),
    "economics_carries_validation_state": g["economics_carries_validation_state"].value_counts().to_dict(),
    "spearman_v1_v2_all_contracts": spearman(g), "within_family": within_family_spearman(g),
}
out["family_rows"] = {
    "n": len(fam_df), "by_dir": fam_df["direction"].value_counts().to_dict(),
    "pick_rule": fam_df["contract_pick_rule"].value_counts().to_dict(),
    "monetisability_by_dir": dist(fam_df, "monetisability_state"), "applicability_by_dir": dist(fam_df, "applicability"),
    "tester_state_matches": fam_df["tester_state_matches"].value_counts(dropna=False).to_dict(),
    "legacy_book_state_by_dir": dist(fam_df, "legacy_book_monetisability_state"),
    "convexity_label_by_dir": dist(fam_df, "convexity_label"), "convexity_distinct": int(fam_df["convexity_score"].round(10).nunique()),
    "spearman_v1_v2": spearman(fam_df),
}
# premise: structural vs reachable LATE BASE net return
prem = {}
for d in ("CALL", "PUT", "ALL"):
    s = g if d == "ALL" else g.loc[g.direction == d]
    s = s.dropna(subset=["net:REACHABLE:LATE:BASE", "net:STRUCTURAL_DISCLOSURE:LATE:BASE"])
    gap = s["net:STRUCTURAL_DISCLOSURE:LATE:BASE"] - s["net:REACHABLE:LATE:BASE"]
    prem[d] = {"n": len(s), "median_reachable_net": None if s.empty else float(s["net:REACHABLE:LATE:BASE"].median()),
               "median_structural_net": None if s.empty else float(s["net:STRUCTURAL_DISCLOSURE:LATE:BASE"].median()),
               "median_gap_pp": None if s.empty else float(gap.median() * 100),
               "share_structural_ge_floor": None if s.empty else float((s["net:STRUCTURAL_DISCLOSURE:LATE:BASE"] >= FLOOR).mean()),
               "share_reachable_ge_floor": None if s.empty else float((s["net:REACHABLE:LATE:BASE"] >= FLOOR).mean()),
               "median_reach_ratio": None if s.empty else float(s["reach_ratio"].median())}
out["premise_structural_vs_reachable_contracts"] = prem
rw = pd.DataFrame(runway)
out["runway_excluded"] = {"contracts": len(rw), "tickers": int(rw["ticker"].nunique()) if len(rw) else 0,
                          "in_display_set": int(rw["in_display"].sum()) if len(rw) else 0,
                          "states": rw["state"].value_counts().to_dict() if len(rw) else {}}
out["elapsed_s"] = round(time.time() - t0, 1)
(HERE / "p12_C_offline_sample.out.json").write_text(json.dumps(out, indent=2, default=str), encoding="utf-8")
print(json.dumps({k: v for k, v in out.items() if k not in ("garch_sub_exceptions",)}, indent=1, default=str)[:6000])
print("exceptions garch:", len(garch_exc), garch_exc[:5])
