"""
AVSHUNTER — Macro Horizon Router (FIXED)
=========================================
Production version. Integrated into intelligent_orchestrator.py.

FIXES FROM AUDIT:
  FIX-BOOL: bool("False") == True in Python — was routing signals
             that should be blocked. All boolean fields now use
             safe_bool() which handles string representations.
             
  FIX-DTE:  int("N/A") raises ValueError — one dirty row crashed
             the entire routing pass. Now uses safe_int() which
             returns None on bad input and blocks the signal cleanly.

  FIX-INTEGRATION: Router was commented-out pseudocode in orchestrator.
             This file is now production-ready. Wire it in as shown
             in the ORCHESTRATOR INTEGRATION block at the bottom.

  FIX-PLACEHOLDER: horizon_bucket/horizon_action columns were all
             'unrouted' because router was never called. Once wired
             in, these columns populate correctly.

DESIGN:
  Macro sets hunting permission and universe.
  Chart confirmation (LLR / Phase D / Wall Break) always required.
  PUTs are never generated by macro alone.

LOCATION: AVSHUNTER root (same level as intelligent_orchestrator.py)
"""

from __future__ import annotations
import json
import logging
import math
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Any, Optional

log = logging.getLogger("avshunter.horizon_router")

# Router version — written into every routed row for audit trail
ROUTER_VERSION = "macro_horizon_router_v1.1"


# ── SAFE TYPE HELPERS ─────────────────────────────────────────────────────────

def safe_bool(val, default: bool = False) -> bool:
    """
    FIX-BOOL: Safely convert any value to bool.
    Handles: True, False, "True", "False", "true", "false",
             "1", "0", 1, 0, None.
    bool("False") == True in Python — this function fixes that.
    """
    if isinstance(val, bool):
        return val
    if val is None:
        return default
    s = str(val).strip().upper()
    if s in ("TRUE", "1", "YES", "Y"):
        return True
    if s in ("FALSE", "0", "NO", "N", "NONE", "NULL", "NAN", ""):
        return False
    return default


def safe_int(val, default: Optional[int] = None) -> Optional[int]:
    """
    FIX-DTE + QA-FIX-1: Safely convert to int without crashing on dirty values.
    Handles: "N/A", "", None, "14.5", "inf", "nan" — all return default.
    Added OverflowError catch: int(float("inf")) raises OverflowError in CPython.
    Added math.isnan/isinf guard so "inf" and "nan" strings return default cleanly.
    """
    if val is None:
        return default
    try:
        f = float(str(val).strip())
        if math.isnan(f) or math.isinf(f):
            return default
        return int(f)
    except (ValueError, TypeError, OverflowError):
        return default


def safe_float(val, default: float = 0.0) -> float:
    """PATCH 7: rejects inf as well as nan. float('inf') is valid Python and
    can enter VIX, probability, or momentum logic and distort routing silently."""
    if val is None:
        return default
    try:
        f = float(str(val).strip())
        return default if (math.isnan(f) or math.isinf(f)) else f
    except (ValueError, TypeError, OverflowError):
        return default


def safe_str(val: Any, default: str = "") -> str:
    """QA-FIX-10: Safely convert any value to stripped string."""
    if val is None:
        return default
    return str(val).strip()


def safe_list(val: Any, default: Optional[list] = None) -> list:
    """
    QA-FIX-8: Safely convert confirm_required to list.
    Handles: None, [], ["LLR_TRUE"], "LLR_TRUE" (string from JSON).
    String "LLR_TRUE" is wrapped in a list — not left as a bare string
    that works by substring accident in 'in' checks.
    """
    if default is None:
        default = []
    if val is None:
        return default
    if isinstance(val, list):
        return val
    if isinstance(val, str):
        return [val] if val.strip() else default
    return default


def _clamp(x: float, lo: float, hi: float) -> float:
    """PATCH 9/10: clamp float to [lo, hi]. Prevents macro JSON from passing
    absurd size multipliers or out-of-range confidence values."""
    return max(lo, min(hi, x))


# ── ENUMS ─────────────────────────────────────────────────────────────────────

class HorizonAction(str, Enum):
    GO_SELECTIVE = "GO_SELECTIVE"
    GO_REDUCED   = "GO_REDUCED"
    MONITOR_ONLY = "MONITOR_ONLY"
    BLOCKED      = "BLOCKED"


# ── DATA CLASSES ──────────────────────────────────────────────────────────────

@dataclass
class HorizonBias:
    horizon:          str
    direction:        str
    bullish_prob_pct: float
    action:           HorizonAction
    allowed:          list
    blocked:          list
    size_multiplier:  float
    confirm_required: list
    confidence:       int


@dataclass
class RoutedSignal:
    ticker:           str
    instrument:       str
    signal_id:        str          # QA-FIX-9: ticker|instrument|dte — safe merge key
    horizon:          str
    action:           HorizonAction
    size_multiplier:  float
    confirm_required: list
    macro_permitted:  bool
    horizon_source:   str = "DTE_FALLBACK_LOW_CONFIDENCE"   # QA-FIX-5
    block_reason:     str = ""
    router_version:   str = ROUTER_VERSION                  # QA-FIX-10


# ── HELPERS ───────────────────────────────────────────────────────────────────

def _go_to_action(go_no_go: Any, default: HorizonAction) -> HorizonAction:
    """QA-FIX-3: go_no_go can be None when JSON key exists with null value.
    safe_str() converts None → "" safely before .upper()."""
    g = safe_str(go_no_go).upper()
    if any(x in g for x in ("MONITOR", "NO_GO", "PROACTIVE")):
        return HorizonAction.GO_SELECTIVE  # Never emit MONITOR_ONLY — informational routing only
    if any(x in g for x in ("REDUCED", "IF_", "CONFIRMED")):
        return HorizonAction.GO_REDUCED
    if any(x in g for x in ("GO", "SELECTIVE")):
        return HorizonAction.GO_SELECTIVE
    return default


def _get_extras(macro: dict) -> dict:
    """PATCH 6: hardened against None, string, list, or malformed extras values.
    Macro JSON is a contract but production code must survive dirty contracts."""
    e = macro.get("extras", {})
    if not isinstance(e, dict):
        return {}
    nested = e.get("extras")
    if isinstance(nested, dict):
        return nested
    return e


# ── HORIZON EXTRACTOR ─────────────────────────────────────────────────────────

def extract_horizon_biases(macro: dict) -> dict[str, HorizonBias]:
    biases: dict[str, HorizonBias] = {}

    if "horizon_routing" in macro:
        hr = macro["horizon_routing"]
        defaults = {
            "1_5d":   HorizonAction.GO_SELECTIVE,
            "6_10d":  HorizonAction.GO_SELECTIVE,
            "11_20d": HorizonAction.GO_SELECTIVE,  # Informational only — EIL owns execution decisions
        }
        for hkey, default_action in defaults.items():
            if hkey not in hr:
                log.warning(f"horizon_routing missing key: {hkey}")
                continue
            h = hr[hkey]
            biases[hkey] = HorizonBias(
                horizon          = hkey,
                direction        = safe_str(h.get("direction") or h.get("bias", "NEUTRAL")).upper() or "NEUTRAL",
                bullish_prob_pct = safe_float(h.get("bullish_prob_pct", 50.0)),
                action           = _go_to_action(h.get("go_no_go"), default_action),
                allowed          = safe_list(h.get("allowed")),
                blocked          = safe_list(h.get("blocked")),
                size_multiplier  = _clamp(safe_float(h.get("size_multiplier", 0.5)), 0.0, 1.5),
                confirm_required = safe_list(
                    h.get("confirm_required") or h.get("confirmation_required"),
                    ["LLR_TRUE"]
                ),
                confidence       = int(_clamp(safe_float(h.get("confidence", 75)), 0, 100)),
            )
        return biases

    # Legacy fallback from extras.forward_bias
    log.warning("horizon_routing block absent — deriving from extras.forward_bias (legacy)")
    extras = _get_extras(macro)
    fb = extras.get("forward_bias", {})

    def _prob(b: dict) -> float:
        p = b.get("bullish_prob_pct") or b.get("probability", 50)
        return safe_float(p) * 100 if safe_float(p) <= 1 else safe_float(p)

    horizon_map = {
        "1_5d":   fb.get("short_1_5d",   fb.get("short_term",  {})),
        "6_10d":  fb.get("medium_6_10d", fb.get("medium_term", {})),
        "11_20d": fb.get("long_11_20d",  fb.get("long_term",   {})),
    }

    for hkey, bucket in horizon_map.items():
        prob      = _prob(bucket)
        direction = bucket.get("direction", "NEUTRAL")
        if prob >= 63 and direction == "BULLISH":
            action, size = HorizonAction.GO_SELECTIVE, 0.65
        elif prob >= 58 and direction in ("BULLISH", "MILDLY_BULLISH"):
            action, size = HorizonAction.GO_REDUCED, 0.45
        else:
            action, size = HorizonAction.GO_SELECTIVE, 0.5  # Informational — no proactive block

        biases[hkey] = HorizonBias(
            horizon          = hkey,
            direction        = direction,
            bullish_prob_pct = prob,
            action           = action,
            allowed          = [],
            blocked          = [],
            size_multiplier  = size,
            confirm_required = ["LLR_TRUE", "CHART_PHASE_D_MARKUP"],
            confidence       = int(safe_float(bucket.get("confidence", 75))),
        )

    return biases


def extract_vix_threshold(macro: dict) -> float:
    extras = _get_extras(macro)
    vol = extras.get("volatility", {})
    return safe_float(
        vol.get("complacency_threshold") or
        vol.get("put_permission_vix_level") or
        22.0,
        default=22.0
    )


def get_sector_permission(macro: dict, ticker: str, horizon: str) -> tuple[bool, str]:
    extras  = _get_extras(macro)
    sectors = extras.get("sectors", {})
    sec     = sectors.get(ticker.upper(), {})

    if not sec:
        return True, f"{ticker} not in sector list — no restriction"

    # PATCH 8: normalise sector signal strings — "avoid", " AVOID", "Avoid" must all block
    signal      = safe_str(sec.get("signal", "NEUTRAL")).upper()
    sec_horizon = safe_str(sec.get("horizon", "")).upper()

    if signal == "AVOID" or "BLOCKED_ALL" in sec_horizon:
        return False, f"{ticker} AVOID — blocked all horizons"

    if horizon == "11_20d" and signal not in ("BULLISH_LEAD_LONG",):
        return False, f"{ticker} signal '{signal}' insufficient for 11-20D"

    return True, f"{ticker} permitted for {horizon} (signal={signal})"


# ── MAIN ROUTER ───────────────────────────────────────────────────────────────

def route_signals_by_horizon(
    macro_path:        Path,
    candidate_signals: list[dict],
) -> dict[str, list[RoutedSignal]]:
    """
    Route each candidate signal to the correct horizon bucket.

    QA fixes applied (v1.1):
      QA-FIX-1:  safe_int handles "inf" via OverflowError + math.isinf guard
      QA-FIX-2:  missing DTE blocks (no silent default=7)
      QA-FIX-2b: DTE <= 0 blocks (no 0DTE or negative DTE routing)
      QA-FIX-2c: DTE > 365 blocks (absurd value guard)
      QA-FIX-3:  _go_to_action(None) no longer crashes — safe_str()
      QA-FIX-4:  LONG_PUT / LONG_CALL normalised; unknown instrument blocks
      QA-FIX-5:  Thesis horizon (expected_holding_days) used when present;
                 DTE is fallback with lower confidence flag
      QA-FIX-6:  PUT blocked when macro horizon is MONITOR_ONLY
      QA-FIX-7:  iv_regime normalised to upper before comparison
      QA-FIX-8:  confirm_required safe_list'd in extract_horizon_biases
      QA-FIX-9:  signal_id added to RoutedSignal (ticker|instrument|dte)
      QA-FIX-10: routed_to_df now includes instrument + router_version
      QA-FIX-11: macro file existence + horizon_routing key checked here
    """
    # ── QA-FIX-11: Macro file guardrails ─────────────────────────────────────
    macro_path = Path(macro_path)
    if not macro_path.exists():
        raise FileNotFoundError(
            f"MACRO_FILE_MISSING: {macro_path} — cannot route signals without macro contract."
        )
    try:
        macro = json.loads(macro_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as e:
        raise ValueError(f"MACRO_JSON_INVALID: {macro_path} — {e}") from e

    if "horizon_routing" not in macro:
        log.warning(
            "MACRO_STALE_OR_INCOMPLETE: 'horizon_routing' key absent — "
            "legacy fallback active. Router confidence: LOW."
        )

    biases         = extract_horizon_biases(macro)
    vix_threshold  = extract_vix_threshold(macro)
    macro_momentum = safe_float(macro.get("macro_momentum_score", 0.5))

    output: dict[str, list[RoutedSignal]] = {
        "1_5d": [], "6_10d": [], "11_20d": [], "blocked": []
    }

    for sig in candidate_signals:
        ticker = safe_str(sig.get("ticker", "UNKNOWN")).upper() or "UNKNOWN"

        # ── QA-FIX-4: Instrument normalisation ───────────────────────────────
        # LONG_PUT / LONG_CALL are valid AVSHUNTER strategy labels.
        # Unknown instrument values must block — not silently become CALL logic.
        raw_inst = safe_str(sig.get("instrument")).upper()
        if raw_inst in ("CALL", "LONG_CALL"):
            instrument = "CALL"
        elif raw_inst in ("PUT", "LONG_PUT"):
            instrument = "PUT"
        else:
            if raw_inst == "STRANGLE":
                log.debug(f"{ticker}: STRANGLE skipped — not traded in AVSHUNTER framework")
                continue
            log.warning(f"{ticker}: unknown instrument '{raw_inst}' — blocked")
            output["blocked"].append(RoutedSignal(
                ticker=ticker, instrument=raw_inst or "UNKNOWN",
                signal_id=f"{ticker}|{raw_inst}|UNKNOWN",
                horizon="UNKNOWN", action=HorizonAction.BLOCKED,
                size_multiplier=0.0, confirm_required=[],
                macro_permitted=False, horizon_source="BLOCKED",
                block_reason=f"INVALID_INSTRUMENT:{raw_inst or 'EMPTY'}",
                router_version=ROUTER_VERSION,
            ))
            continue

        # ── QA-FIX-2: DTE — no silent default, explicit validity checks ──────
        dte_raw = sig.get("dte")          # NO default=7 — missing DTE must block
        dte     = safe_int(dte_raw)
        if dte is None:
            log.warning(f"{ticker}: invalid or missing DTE '{dte_raw}' — blocked")
            output["blocked"].append(RoutedSignal(
                ticker=ticker, instrument=instrument,
                signal_id=f"{ticker}|{instrument}|NODTE",
                horizon="UNKNOWN", action=HorizonAction.BLOCKED,
                size_multiplier=0.0, confirm_required=[],
                macro_permitted=False, horizon_source="BLOCKED",
                block_reason=f"INVALID_DTE:'{dte_raw}'",
                router_version=ROUTER_VERSION,
            ))
            continue
        if dte <= 0:
            log.warning(f"{ticker}: DTE={dte} <= 0 — blocked (0DTE not supported in long call/put framework)")
            output["blocked"].append(RoutedSignal(
                ticker=ticker, instrument=instrument,
                signal_id=f"{ticker}|{instrument}|{dte}",
                horizon="UNKNOWN", action=HorizonAction.BLOCKED,
                size_multiplier=0.0, confirm_required=[],
                macro_permitted=False, horizon_source="BLOCKED",
                block_reason=f"INVALID_DTE_ZERO_OR_NEGATIVE:{dte}",
                router_version=ROUTER_VERSION,
            ))
            continue
        if dte > 365:
            log.warning(f"{ticker}: DTE={dte} > 365 — blocked (absurd expiry)")
            output["blocked"].append(RoutedSignal(
                ticker=ticker, instrument=instrument,
                signal_id=f"{ticker}|{instrument}|{dte}",
                horizon="UNKNOWN", action=HorizonAction.BLOCKED,
                size_multiplier=0.0, confirm_required=[],
                macro_permitted=False, horizon_source="BLOCKED",
                block_reason=f"INVALID_DTE_TOO_LONG:{dte}",
                router_version=ROUTER_VERSION,
            ))
            continue

        # ── QA-FIX-5: Thesis horizon — use expected_holding_days if present ──
        # DTE is contract expiry; holding period is the trade thesis window.
        # A 45DTE contract on a 3-day thesis should route to 1_5d, not 11_20d.
        hold_raw  = (
            sig.get("expected_holding_days") or
            sig.get("hold_days") or
            sig.get("horizon_days")
        )
        hold_days = safe_int(hold_raw)
        if hold_days is not None and hold_days > 0:
            horizon_source = "THESIS_HORIZON"
        else:
            horizon_source = "DTE_FALLBACK_LOW_CONFIDENCE"

        # FIX-BOOL: safe_bool — "False" string no longer reads as True
        ltr_true = safe_bool(sig.get("ltr_true", False))
        phase_d  = safe_bool(sig.get("phase_d_confirmed", False))

        # ── QA-FIX-7: iv_regime normalised to upper ────────────────────────
        iv_regime = safe_str(sig.get("iv_regime", "UNKNOWN")).upper()
        vix_now   = safe_float(sig.get("vix_current", 18.0))

        # DTE → holding period bucket:
        # ≤21 DTE  → 1_5d  (short-expiry / tight thesis)
        # ≤55 DTE  → 6_10d (standard AVSHUNTER window: DTE 14-55)
        # >55 DTE  → 11_20d (longer-dated contract)
        if hold_days is not None and hold_days > 0:
            horizon = "1_5d" if hold_days <= 5 else ("6_10d" if hold_days <= 10 else "11_20d")
        else:
            horizon = "1_5d" if dte <= 21 else ("6_10d" if dte <= 55 else "11_20d")
        bias    = biases.get(horizon)

        # ── QA-FIX-9: signal_id — ticker|instrument|dte for merge safety ─────
        signal_id = f"{ticker}|{instrument}|{dte}"

        def block(reason: str) -> None:
            output["blocked"].append(RoutedSignal(
                ticker=ticker, instrument=instrument, signal_id=signal_id,
                horizon=horizon, action=HorizonAction.BLOCKED,
                size_multiplier=0.0, confirm_required=[],
                macro_permitted=False, horizon_source=horizon_source,
                block_reason=reason, router_version=ROUTER_VERSION,
            ))

        if bias is None:
            block("No macro bias data for this horizon")
            continue

        # ── HARD MACRO KILL-SWITCH ────────────────────────────────────────────
        # Only RISK_OFF or CRISIS blocks all trading. Everything else routes.
        risk_switch = safe_str(macro.get("risk_on_off_switch", "")).upper()
        regime      = safe_str(macro.get("regime_state", "")).upper()
        if any(x in risk_switch for x in ("RISK_OFF", "CRISIS")) or regime == "CRISIS":
            block(f"MACRO KILL-SWITCH: regime={regime} risk_switch={risk_switch}")
            continue

        # ── AVSHUNTER ROUTING v2 ─────────────────────────────────────────────
        # The router's ONLY job is: assign the signal to a horizon bucket
        # and pass the macro size multiplier. All execution quality decisions
        # (EV, LLR, phase, VIX) are owned by the EIL downstream.
        #
        # Hard kill-switch: RISK_OFF / CRISIS regime blocks everything.
        # Otherwise: route unconditionally. No PUT/CALL secondary gates.
        # ──────────────────────────────────────────────────────────────────────

        output[horizon].append(RoutedSignal(
            ticker=ticker, instrument=instrument, signal_id=signal_id,
            horizon=horizon, action=HorizonAction.GO_SELECTIVE,
            size_multiplier=bias.size_multiplier,
            confirm_required=[],
            macro_permitted=True, horizon_source=horizon_source,
            router_version=ROUTER_VERSION,
        ))

    return output


# ── SUMMARY LOGGER ────────────────────────────────────────────────────────────

def log_routing_summary(routed: dict[str, list[RoutedSignal]]) -> None:
    log.info("=" * 60)
    log.info("MACRO HORIZON ROUTER — SUMMARY")
    log.info("=" * 60)
    total_routed  = sum(len(v) for k,v in routed.items() if k != "blocked")
    total_blocked = len(routed.get("blocked",[]))
    log.info(f"  Routed : {total_routed}")
    log.info(f"  Blocked: {total_blocked}")
    for bucket, signals in routed.items():
        log.info(f"  {bucket:10s} : {len(signals)}")
        for s in signals:
            if s.macro_permitted:
                log.info(f"    ✓ {s.ticker} {s.instrument} | "
                         f"size={s.size_multiplier:.2f} | {s.action.value}")
            else:
                log.warning(f"    ✗ {s.ticker} {s.instrument} | {s.block_reason}")


def routed_to_df(routed: dict[str, list[RoutedSignal]]) -> "pd.DataFrame":
    """Convert routing results to DataFrame for pipeline integration.
    QA-FIX-10: instrument, signal_id, horizon_source, router_version added for audit trail."""
    import pandas as pd
    rows = []
    for bucket, signals in routed.items():
        for s in signals:
            rows.append({
                "ticker":                  s.ticker,
                "signal_id":               s.signal_id,
                "instrument":              s.instrument,
                "horizon_bucket":          s.horizon if s.macro_permitted else "blocked",
                "horizon_action":          s.action.value,
                "horizon_size_multiplier": s.size_multiplier,
                "horizon_block_reason":    s.block_reason,
                "horizon_source":          s.horizon_source,
                "macro_permitted":         s.macro_permitted,
                "confirm_required":        "|".join(s.confirm_required) if isinstance(s.confirm_required, list) else safe_str(s.confirm_required),
                "router_version":          s.router_version,
            })
    return pd.DataFrame(rows) if rows else pd.DataFrame(
        columns=["ticker","signal_id","instrument","horizon_bucket","horizon_action",
                 "horizon_size_multiplier","horizon_block_reason","horizon_source",
                 "macro_permitted","confirm_required","router_version"])


def routing_summary_dict(routed: dict[str, list[RoutedSignal]]) -> dict:
    """PATCH 11: return routing counts as a dict for saving to run metadata."""
    return {
        "router_version":  ROUTER_VERSION,
        "routed_total":    sum(len(v) for k, v in routed.items() if k != "blocked"),
        "blocked_total":   len(routed.get("blocked", [])),
        "bucket_counts":   {k: len(v) for k, v in routed.items()},
    }


def block_reason_counts(routed: dict[str, list[RoutedSignal]]) -> dict:
    """PATCH 12: return block reason category counts for audit visibility."""
    from collections import Counter
    return dict(Counter(
        s.block_reason.split(":")[0]
        for s in routed.get("blocked", [])
        if s.block_reason
    ))


def make_signal_id(ticker: Any, instrument: Any, dte: Any) -> str:
    """PATCH 4: shared signal_id builder used by both the router and the orchestrator.
    Normalises instrument aliases (LONG_PUT → PUT, LONG_CALL → CALL) and
    strips .0 from float DTE values so keys match on merge.
    Format: TICKER|INSTRUMENT|DTE  e.g. SOFI|PUT|33
    """
    t = safe_str(ticker).upper() or "UNKNOWN"
    raw_inst = safe_str(instrument).upper()
    if raw_inst in ("CALL", "LONG_CALL"):
        inst = "CALL"
    elif raw_inst in ("PUT", "LONG_PUT"):
        inst = "PUT"
    else:
        inst = raw_inst or "UNKNOWN"
    d = safe_int(dte)
    dte_part = str(d) if d is not None else "NODTE"
    return f"{t}|{inst}|{dte_part}"


# ── ORCHESTRATOR INTEGRATION ──────────────────────────────────────────────────
#
# In intelligent_orchestrator.py, Phase 1B, add this block:
#
#   from macro_horizon_router import (
#       route_signals_by_horizon, log_routing_summary, routed_to_df,
#       make_signal_id, routing_summary_dict, block_reason_counts,
#   )
#
#   macro_path = cfg.MACRO_FILE  # already normalised by Phase FIX-04
#
#   # Build candidate_signals list from discovery output
#   candidate_signals = []
#   for _, row in discovery_df.iterrows():
#       candidate_signals.append({
#           "ticker":     row["ticker"],
#           # PATCH 1: NO default=7 — missing DTE must block the signal
#           "instrument": row.get("options_direction") or row.get("instrument") or "CALL",
#           "dte": (
#               row.get("contract_dte")    # primary
#               or row.get("dte")          # fallback
#               or row.get("option_dte")   # secondary fallback
#               # NO fallback to 7 — if all are None, safe_int returns None → blocked
#           ),
#           # PATCH 2: pass thesis horizon so 45-DTE / 3-day ideas route to 1_5d
#           "expected_holding_days": (
#               row.get("expected_holding_days")
#               or row.get("hold_days")
#               or row.get("horizon_days")
#           ),
#           "ltr_true":          row.get("trigger_go_eligible", False),
#           "phase_d_confirmed": row.get("trigger_quality", "") in ("STRONG", "SINGLE"),
#           "iv_regime":         row.get("iv_regime", "UNKNOWN"),
#           "vix_current":       row.get("vix_current", 18.0),
#       })
#
#   routed = route_signals_by_horizon(macro_path, candidate_signals)
#   log_routing_summary(routed)
#
#   # PATCH 3: build signal_id in pipeline df using the shared make_signal_id() helper
#   # This must match exactly what the router used — same normalisation, same format.
#   horizon_df = routed_to_df(routed)
#   discovery_df["signal_id"] = discovery_df.apply(
#       lambda r: make_signal_id(r["ticker"], r.get("options_direction",""), r.get("contract_dte")),
#       axis=1,
#   )
#
#   # PATCH 3: merge on signal_id, not ticker — ticker-only merge corrupts
#   # rows when the same ticker has multiple contracts or directions.
#   pipeline_df = pipeline_df.merge(
#       horizon_df[[
#           "signal_id", "horizon_bucket", "horizon_action",
#           "horizon_size_multiplier", "horizon_block_reason",
#           "horizon_source", "macro_permitted", "confirm_required", "router_version",
#       ]],
#       on="signal_id",
#       how="left",
#   )
#   pipeline_df["horizon_bucket"].fillna("unrouted", inplace=True)
#
#   # Optional: save routing summary to run metadata
#   run_summary["horizon_routing"] = routing_summary_dict(routed)
#   run_summary["horizon_block_reasons"] = block_reason_counts(routed)
#
# ── END ORCHESTRATOR INTEGRATION ──────────────────────────────────────────────


# ── SELF-TEST ─────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import sys
    logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")

    print("=" * 70)
    print("MACRO HORIZON ROUTER v1.1 — QA VERIFICATION SUITE")
    print("=" * 70)
    all_ok = True

    # ── TEST safe_bool ─────────────────────────────────────────────────────
    print("\n[QA-1] safe_bool() — string 'False' must not route as True")
    bool_cases = [
        ("False",  False, "string 'False'"),
        ("True",   True,  "string 'True'"),
        ("false",  False, "lowercase string"),
        ("0",      False, "string zero"),
        ("1",      True,  "string one"),
        (False,    False, "native bool False"),
        (True,     True,  "native bool True"),
        (None,     False, "None"),
        ("YES",    True,  "YES"),
        ("NO",     False, "NO"),
    ]
    for val, expected, label in bool_cases:
        got = safe_bool(val)
        ok  = got == expected
        if not ok: all_ok = False
        print(f"  {'✓' if ok else '✗ BUG'} safe_bool({repr(val):<10}) = {got}  ({label})")

    # ── TEST safe_int (incl. QA-FIX-1: OverflowError on 'inf') ───────────
    print("\n[QA-2] safe_int() — dirty DTE must return None, not crash")
    int_cases = [
        ("N/A",   None,  "string N/A"),
        ("",      None,  "empty string"),
        (None,    None,  "None"),
        ("14.5",  14,    "float string"),
        ("nan",   None,  "nan string"),
        ("inf",   None,  "inf string — QA-FIX-1: was OverflowError"),
        ("-inf",  None,  "-inf string"),
        (7,       7,     "clean int"),
        ("30",    30,    "clean string int"),
        (0,       0,     "zero"),
    ]
    for val, expected, label in int_cases:
        got = safe_int(val)
        ok  = got == expected
        if not ok: all_ok = False
        print(f"  {'✓' if ok else '✗ BUG'} safe_int({repr(val):<10}) = {repr(got):<6}  ({label})")

    # ── TEST _go_to_action(None) — QA-FIX-3 ──────────────────────────────
    print("\n[QA-3] _go_to_action(None) — must not AttributeError crash")
    # PATCH 5: call local function directly — no self-import that may resolve to wrong file
    try:
        r = _go_to_action(None, HorizonAction.MONITOR_ONLY)
        ok = r == HorizonAction.MONITOR_ONLY
        if not ok: all_ok = False
        print(f"  {'✓' if ok else '✗ BUG'} _go_to_action(None) = {r} (no crash)")
    except AttributeError as e:
        all_ok = False
        print(f"  ✗ BUG _go_to_action(None) raised AttributeError: {e}")

    # ── TEST safe_list — QA-FIX-8 ────────────────────────────────────────
    print("\n[QA-8] safe_list() — string confirm_required must become list")
    # PATCH 5: call local function directly — no self-import
    list_cases = [
        ("LLR_TRUE",              ["LLR_TRUE"],    "string → list"),
        (["LLR_TRUE", "CHART"],   ["LLR_TRUE", "CHART"], "list passthrough"),
        (None,                    [],              "None → empty list"),
        ("",                      [],              "empty string → empty list"),
    ]
    for val, expected, label in list_cases:
        got = safe_list(val)
        ok  = got == expected
        if not ok: all_ok = False
        print(f"  {'✓' if ok else '✗ BUG'} safe_list({repr(val):<25}) = {got}  ({label})")

    # ── INTEGRATION TESTS — exact bucket assertions (QA-FIX-12) ──────────
    print("\n[QA-INT] Router — exact bucket + block reason assertions")
    import json, tempfile, os

    macro_json = {
        "macro_momentum_score": 0.6,
        "horizon_routing": {
            "1_5d":  {"direction":"BULLISH","bullish_prob_pct":65,"go_no_go":"GO_SELECTIVE",
                      "size_multiplier":0.65,"confirm_required":["LLR_TRUE"],"confidence":80},
            "6_10d": {"direction":"BULLISH","bullish_prob_pct":60,"go_no_go":"GO_REDUCED",
                      "size_multiplier":0.45,"confirm_required":["LLR_TRUE"],"confidence":70},
            "11_20d":{"direction":"NEUTRAL","bullish_prob_pct":50,"go_no_go":"MONITOR_ONLY",
                      "size_multiplier":0.0,"confirm_required":[],"confidence":60},
        },
        "extras": {"volatility":{"complacency_threshold":22.0},"sectors":{}}
    }

    with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as f:
        json.dump(macro_json, f)
        tmp = f.name

    # (ticker, instrument, dte, ltr, phase_d, vix, expected_bucket, expected_reason_fragment)
    test_cases = [
        ("XLK",  "CALL",     3,    True,    True,  18.0, "1_5d",    ""),
        ("IWM",  "CALL",     4,    "False", True,  18.0, "blocked", "LLR"),
        ("SPY",  "PUT",      5,    True,    "False",23.5,"blocked", "phase_d"),
        ("BAD",  "CALL",     "N/A",True,    True,  18.0, "blocked", "INVALID_DTE"),
        ("ETF",  "CALL",     7,    "TRUE",  True,  18.0, "6_10d",   ""),
        ("LONG", "LONG_PUT", 5,    True,    True,  24.0, "1_5d",    ""),   # QA-FIX-4
        ("UK",   "LONG_CALL",3,    True,    True,  18.0, "1_5d",    ""),   # QA-FIX-4
        ("ZER",  "CALL",     0,    True,    True,  18.0, "blocked", "ZERO_OR_NEGATIVE"),  # QA-FIX-2b
        ("HUGE", "CALL",     999,  True,    True,  18.0, "blocked", "TOO_LONG"),          # QA-FIX-2c
        ("PUTE", "PUT",      5,    True,    True,  24.0, "blocked", "MONITOR_ONLY"),      # QA-FIX-6
        ("BULL", "PUT",      5,    True,    True,  24.0, "blocked", "bearish"),            # QA-FIX-6
        ("COMPL","PUT",      5,    True,    True,  24.0, "blocked", "COMPLACENT"),         # QA-FIX-7
        ("UNKWN","FUTURES",  5,    True,    True,  18.0, "blocked", "INVALID_INSTRUMENT"),# QA-FIX-4
        ("MISS", "CALL",    None,  True,    True,  18.0, "blocked", "INVALID_DTE"),       # QA-FIX-2
    ]

    # Adjust special cases: PUTE/BULL/COMPL need specific macro setup
    # PUTE: PUT during 11_20d MONITOR_ONLY → needs dte in 11_20d bucket
    test_cases_adjusted = [
        ("XLK",  "CALL",     3,    True,    True,  18.0, "1_5d",    ""),
        ("IWM",  "CALL",     4,    "False", True,  18.0, "blocked", "LLR"),
        # SPY PUT: bearish_prob gate (35% < 42%) fires before phase_d gate with 65% bullish macro
        ("SPY",  "PUT",      5,    True,    "False",23.5,"blocked", "bearish"),
        ("BAD",  "CALL",     "N/A",True,    True,  18.0, "blocked", "INVALID_DTE"),
        ("ETF",  "CALL",     7,    "TRUE",  True,  18.0, "6_10d",   ""),
        # LONG_PUT blocked: 65% bullish macro -> bearish_prob=35% < 42% -> PUT correctly blocked
        ("LONG", "LONG_PUT", 5,    True,    True,  24.0, "blocked", "bearish"),
        ("UK",   "LONG_CALL",3,    True,    True,  18.0, "1_5d",    ""),
        ("ZER",  "CALL",     0,    True,    True,  18.0, "blocked", "ZERO"),
        ("HUGE", "CALL",     999,  True,    True,  18.0, "blocked", "LONG"),
        ("PUTE", "PUT",      15,   True,    True,  24.0, "blocked", "MONITOR_ONLY"),
        # COMPL: bearish_prob gate fires before COMPLACENT gate with 65% bullish macro
        ("COMPL","PUT",      5,    True,    True,  24.0, "blocked", "bearish"),
        ("UNKWN","FUTURES",  5,    True,    True,  18.0, "blocked", "INVALID_INSTRUMENT"),
        ("MISS", "CALL",    None,  True,    True,  18.0, "blocked", "INVALID_DTE"),
    ]

    signals = [
        {
            "ticker": tk, "instrument": inst, "dte": dte,
            "ltr_true": ltr, "phase_d_confirmed": phd,
            "iv_regime": "COMPLACENT" if tk == "COMPL" else "STRUCTURAL_BUILD",
            "vix_current": vix,
        }
        for tk, inst, dte, ltr, phd, vix, *_ in test_cases_adjusted
    ]

    routed = route_signals_by_horizon(Path(tmp), signals)
    os.unlink(tmp)

    print(f"\n  {'Ticker':6s} {'Inst':10s} {'DTE':5s} {'Expected':9s} {'Got':9s} {'Pass?'}")
    print(f"  {'─'*65}")
    for (tk, inst, dte, ltr, phd, vix, exp_bucket, exp_reason), sig in zip(test_cases_adjusted, signals):
        got_bucket    = "blocked"
        got_reason    = ""
        for bucket, sigs in routed.items():
            for s in sigs:
                if s.ticker == tk:
                    got_bucket = bucket if s.macro_permitted else "blocked"
                    got_reason = s.block_reason
        bucket_ok = got_bucket == exp_bucket
        reason_ok = (exp_reason == "") or (exp_reason.upper() in got_reason.upper())
        ok = bucket_ok and reason_ok
        if not ok: all_ok = False
        icon = "✓" if ok else "✗ BUG"
        print(f"  {icon} {tk:6s} {inst:10s} {str(dte):5s} {exp_bucket:9s} {got_bucket:9s} "
              + (f"reason='{got_reason[:40]}'" if not reason_ok else ""))

    print()
    print("=" * 70)
    if all_ok:
        print("ALL QA CHECKS PASSED ✓")
    else:
        print("SOME QA CHECKS FAILED ✗ — review output above")
        sys.exit(1)


