# Targeted daily option-chain backfill: old pipeline top-10-per-run recommendations, live days only.
# Prepared 18 Sep 2026 for ACK (Enhancements/research/legacy_signals). Run from the repo root ONLY after the evening run
# has finished - never while a pipeline is running. Already-captured (ticker, session) pairs are skipped by the tool's audit.
# Cost measured from backfill_audit: ~1 credit per ticker-session, so ~1,100 credits in total. Superseded by backfill_all_commands.ps1.
# To preview a line without spending credits, run it without ' --execute'.
$ErrorActionPreference = 'Stop'

venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-05-26 --weekday 1 --years 0 --tickers AMZN,B,BHP,CALM,CRCL,GDS,GLD,INTU,IREN,LOGI,MNDY,MSTR,NOW,PAAS,PFE,TSM,UNH,WMT --credit-cap 360 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-05-27 --weekday 2 --years 0 --tickers AMZN,APLD,B,BHP,CALM,CRCL,CVX,GDS,GLD,HUT,INTU,IREN,LOGI,MNDY,MSTR,NOW,OKE,ONDS,OVV,PAAS,PFE,TSM,UNH,VLO,WMT --credit-cap 500 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-05-28 --weekday 3 --years 0 --tickers AMZN,APLD,B,BHP,CALM,CRCL,CVX,GDS,GLD,HUT,INTU,IREN,LOGI,MNDY,MSTR,NOW,OKE,ONDS,OVV,PAAS,PFE,TSM,UNH,VLO,WMT --credit-cap 500 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-06-01 --weekday 0 --years 0 --tickers AMZN,APLD,B,BE,BHP,CALM,CLX,CRCL,CVX,GDS,GLD,HUT,INTU,IREN,JNJ,LOGI,MNDY,MSTR,NOW,OKE,ONDS,OVV,PAAS,PFE,PM,TSM,UNH,VLO,WMT --credit-cap 580 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-06-02 --weekday 1 --years 0 --tickers AMZN,APLD,B,BE,BHP,CALM,CLX,CRCL,CVX,GDS,GLD,HUT,INTU,IREN,JNJ,LOGI,MNDY,MSTR,NOW,OKE,ONDS,OVV,PAAS,PFE,PM,TSM,UNH,VLO,WMT --credit-cap 580 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-06-03 --weekday 2 --years 0 --tickers AMZN,APLD,B,BE,BHP,CALM,CLX,CRCL,CVX,GDS,GLD,HUT,INTU,IREN,JNJ,LOGI,MNDY,MSTR,NOW,OKE,ONDS,OVV,PAAS,PFE,PM,TSM,UNH,VLO,WMT --credit-cap 580 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-06-04 --weekday 3 --years 0 --tickers AMZN,APLD,B,BE,BHP,BKSY,CALM,CLX,CRCL,CVX,GDS,GLD,HPQ,HUBS,HUT,INTU,IREN,JNJ,LOGI,MNDY,MSTR,NOW,OKE,ONDS,OVV,PAAS,PATH,PFE,PM,RKLB,ROST,SLV,SOFI,TSM,UNH,VLO,WMT --credit-cap 740 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-06-08 --weekday 0 --years 0 --tickers AMZN,APLD,B,BE,BHP,BKSY,CALM,CLX,CRCL,CVX,GDS,GLD,HPQ,HUBS,HUT,INTU,IREN,JNJ,LOGI,MNDY,MSTR,NOW,OKE,ONDS,OVV,PAAS,PATH,PFE,PM,RKLB,ROST,SLV,SOFI,TSM,UNH,VLO,WMT --credit-cap 740 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-06-09 --weekday 1 --years 0 --tickers AMZN,APLD,B,BE,BHP,BKSY,CALM,CLX,CRCL,CVX,GDS,GLD,HPQ,HUBS,HUT,INTU,IREN,JNJ,LOGI,MNDY,MSTR,NOW,OKE,ONDS,OVV,PAAS,PATH,PFE,PM,RKLB,ROST,SLV,SOFI,TSM,UNH,VLO,WMT --credit-cap 740 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-06-10 --weekday 2 --years 0 --tickers AMZN,APLD,B,BE,BHP,BKSY,CALM,CLX,CRCL,CVX,GDS,GLD,HPQ,HUBS,HUT,INTU,IREN,JNJ,LOGI,MNDY,MSTR,NOW,OKE,ONDS,OVV,PAAS,PATH,PFE,PM,RKLB,ROST,SLV,SOFI,TSM,UNH,VLO,WMT --credit-cap 740 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-06-11 --weekday 3 --years 0 --tickers AMZN,APLD,B,BE,BHP,BKSY,CALM,CLX,CRCL,CVX,GDS,GLD,HPQ,HUBS,HUT,INTU,IREN,JNJ,LOGI,MNDY,MSTR,NOW,OKE,ONDS,OVV,PAAS,PATH,PFE,PM,RKLB,ROST,SLV,SOFI,TSM,UNH,VLO,WMT --credit-cap 740 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-06-15 --weekday 0 --years 0 --tickers AMZN,APLD,B,BE,BHP,BIDU,BKSY,CALM,CLX,CRCL,CVX,FIG,GDS,GLD,HOOD,HPQ,HUBS,HUT,IBM,INTU,IREN,JNJ,KD,LOGI,MNDY,MSTR,NOW,OKE,ONDS,OVV,PAAS,PATH,PFE,PM,RBRK,RKLB,ROST,SLV,SOFI,TSM,UNH,VLO,WMT --credit-cap 860 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-06-16 --weekday 1 --years 0 --tickers AMZN,APLD,B,BE,BHP,BIDU,BKSY,CALM,CLX,CRCL,CVX,FIG,GDS,GLD,HOOD,HPQ,HUBS,HUT,IBM,INTU,IREN,JNJ,KD,LOGI,MNDY,MSTR,NOW,OKE,ONDS,OVV,PAAS,PATH,PFE,PM,RBRK,RKLB,ROST,SLV,SOFI,TSM,UNH,VLO,WMT --credit-cap 860 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-06-17 --weekday 2 --years 0 --tickers AMZN,APLD,B,BE,BHP,BIDU,BKSY,CALM,CLX,CRCL,CVX,FIG,GDS,GLD,HOOD,HPQ,HUBS,HUT,IBM,INTU,IREN,JNJ,KD,LOGI,MNDY,MSTR,NOW,OKE,ONDS,OVV,PAAS,PATH,PFE,PM,RBRK,RKLB,ROST,SLV,SOFI,TSM,UNH,VLO,WMT --credit-cap 860 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-06-18 --weekday 3 --years 0 --tickers AMZN,APLD,B,BE,BHP,BIDU,BKSY,CALM,CLX,CRCL,CVX,FIG,GDS,GLD,HOOD,HPQ,HUBS,HUT,IBM,INTU,IREN,JNJ,KD,LOGI,MNDY,MSTR,NOW,OKE,ONDS,OVV,PAAS,PATH,PFE,PM,RBRK,RKLB,ROST,SLV,SOFI,TSM,UNH,VLO,WMT --credit-cap 860 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-06-22 --weekday 0 --years 0 --tickers BE,BIDU,BKSY,FIG,GLD,HOOD,HPQ,HUBS,IBM,KD,MSTR,OKE,ONDS,PATH,PM,RBRK,RKLB,ROST,SLV,SOFI,WMT --credit-cap 420 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-06-23 --weekday 1 --years 0 --tickers BE,BIDU,BKSY,FIG,GLD,HOOD,HPQ,HUBS,IBM,KD,MSTR,OKE,ONDS,PATH,PM,RBRK,RKLB,ROST,SLV,SOFI,WMT --credit-cap 420 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-06-24 --weekday 2 --years 0 --tickers BE,BIDU,BKSY,FIG,GLD,HOOD,HPQ,HUBS,IBM,KD,MSTR,OKE,ONDS,PATH,PM,RBRK,RKLB,ROST,SLV,SOFI,WMT --credit-cap 420 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-06-25 --weekday 3 --years 0 --tickers BE,BIDU,BKSY,FIG,GLD,HOOD,HPQ,HUBS,IBM,KD,MSTR,OKE,ONDS,PATH,PM,RBRK,RKLB,ROST,SLV,SOFI,WMT --credit-cap 420 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-06-29 --weekday 0 --years 0 --tickers BIDU,BKSY,FIG,GLD,HOOD,HUBS,IBM,KD,OKE,ONDS,PATH,PM,RBRK,RKLB,ROST,SLV,SOFI --credit-cap 340 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-06-30 --weekday 1 --years 0 --tickers BIDU,BKSY,FIG,GLD,HOOD,HUBS,IBM,KD,ONDS,PATH,RBRK,RKLB,ROST,SLV,SOFI --credit-cap 300 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-07-01 --weekday 2 --years 0 --tickers BIDU,BKSY,FIG,HOOD,HUBS,IBM,KD,ONDS,PATH,RBRK,RKLB,ROST,SOFI --credit-cap 260 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-07-02 --weekday 3 --years 0 --tickers BIDU,BKSY,FIG,HOOD,HUBS,IBM,KD,ONDS,PATH,RBRK,RKLB,ROST,SOFI --credit-cap 260 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-07-06 --weekday 0 --years 0 --tickers BIDU,BKSY,FIG,HOOD,HUBS,IBM,KD,RBRK,ROST --credit-cap 180 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-07-07 --weekday 1 --years 0 --tickers BIDU,FIG,HOOD,IBM,KD,RBRK --credit-cap 120 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-07-08 --weekday 2 --years 0 --tickers BIDU,FIG,HOOD,IBM,KD,RBRK --credit-cap 120 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-07-09 --weekday 3 --years 0 --tickers BIDU,FIG,HOOD,IBM,KD,RBRK --credit-cap 120 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-07-13 --weekday 0 --years 0 --tickers KD,RBRK --credit-cap 50 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-07-14 --weekday 1 --years 0 --tickers KD,RBRK --credit-cap 50 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-07-16 --weekday 3 --years 0 --tickers ALGM,CVX,DIS,KLAC,LRCX,PFE,THC,U,UTI,VG --credit-cap 200 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-07-20 --weekday 0 --years 0 --tickers ALGM,CVX,DIS,KLAC,LRCX,PFE,THC,U,UTI,VG --credit-cap 200 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-07-21 --weekday 1 --years 0 --tickers ALGM,CVX,DIS,KLAC,LRCX,PFE,THC,U,UTI,VG --credit-cap 200 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-07-22 --weekday 2 --years 0 --tickers ALGM,CVX,DIS,KLAC,LRCX,PFE,THC,U,UTI,VG --credit-cap 200 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-07-23 --weekday 3 --years 0 --tickers ALGM,BABA,CVX,DIS,GOOGL,HOOD,IWM,KLAC,LRCX,NKE,NVDA,NVS,OKE,PFE,TEM,THC,U,UTI,VG --credit-cap 380 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-07-27 --weekday 0 --years 0 --tickers ALGM,BABA,CVX,DIS,GOOGL,HOOD,IWM,KLAC,LRCX,NKE,NVDA,NVS,OKE,PFE,TEM,THC,U,UTI,VG --credit-cap 380 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-07-28 --weekday 1 --years 0 --tickers ALGM,BABA,CVX,DIS,GOOGL,HOOD,IWM,KLAC,LRCX,NKE,NVDA,NVS,OKE,PFE,TEM,THC,U,UTI,VG --credit-cap 380 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-07-29 --weekday 2 --years 0 --tickers ALGM,BABA,CVX,DIS,GOOGL,HOOD,IWM,KLAC,LRCX,NKE,NVDA,NVS,OKE,PFE,TEM,THC,U,UTI,VG --credit-cap 380 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-07-30 --weekday 3 --years 0 --tickers ALGM,BABA,CVX,DIS,GOOGL,HOOD,IWM,KLAC,LRCX,NKE,NVDA,NVS,OKE,PFE,TEM,THC,U,UTI,VG --credit-cap 380 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-08-03 --weekday 0 --years 0 --tickers ALGM,CLX,ELV,FXI,GOOGL,HOOD,IWM,KLAC,LRCX,NKE,NOW,NVDA,NVS,OKE,PEP,PFE,STZ,T,TEM,THC,U,UTI,VG,VZ,WMT --credit-cap 500 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-08-04 --weekday 1 --years 0 --tickers ALGM,CLX,ELV,FXI,GOOGL,HOOD,IWM,KLAC,LRCX,NKE,NOW,NVDA,NVS,OKE,PEP,PFE,STZ,T,TEM,THC,U,UTI,VG,VZ,WMT --credit-cap 500 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-08-05 --weekday 2 --years 0 --tickers ALGM,CLX,ELV,FXI,GOOGL,HOOD,IWM,KLAC,LRCX,NKE,NOW,NVDA,NVS,OKE,PEP,PFE,STZ,T,TEM,THC,U,UTI,VG,VZ,WMT --credit-cap 500 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-08-06 --weekday 3 --years 0 --tickers ALGM,CLX,ELV,FXI,GOOGL,HOOD,IWM,KLAC,LRCX,NKE,NOW,NVDA,NVS,OKE,PEP,PFE,STZ,T,TEM,THC,U,UTI,VG,VZ,WMT --credit-cap 500 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-08-10 --weekday 0 --years 0 --tickers ALGM,CLX,ELV,FXI,GOOGL,HOOD,IWM,KLAC,LRCX,NKE,NOW,NVDA,NVS,OKE,PEP,STZ,T,TEM,THC,U,UTI,VG,VZ,WMT --credit-cap 480 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-08-11 --weekday 1 --years 0 --tickers ALGM,CLX,ELV,FXI,GOOGL,HOOD,IWM,KLAC,LRCX,NKE,NOW,NVDA,NVS,OKE,PEP,STZ,T,TEM,THC,U,UTI,VG,VZ,WMT --credit-cap 480 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-08-12 --weekday 2 --years 0 --tickers ALGM,CLX,ELV,FXI,GOOGL,HOOD,IWM,KLAC,LRCX,NKE,NOW,NVDA,NVS,OKE,PEP,STZ,T,TEM,THC,U,UTI,VG,VZ,WMT --credit-cap 480 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-08-13 --weekday 3 --years 0 --tickers ALGM,CLX,ELV,FXI,GOOGL,HOOD,IWM,KLAC,LRCX,NKE,NOW,NVDA,NVS,OKE,PEP,STZ,T,TEM,THC,U,UTI,VG,VZ,WMT --credit-cap 480 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-08-17 --weekday 0 --years 0 --tickers CLX,ELV,FXI,GOOGL,HOOD,NKE,NOW,NVDA,NVS,OKE,PEP,STZ,T,TEM,WMT --credit-cap 300 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-08-18 --weekday 1 --years 0 --tickers CLX,ELV,FXI,GOOGL,HOOD,NKE,NOW,NVDA,NVS,OKE,PEP,STZ,T,TEM,WMT --credit-cap 300 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-08-19 --weekday 2 --years 0 --tickers CLX,ELV,FXI,GOOGL,HOOD,NKE,NOW,NVDA,NVS,OKE,PEP,STZ,T,TEM,WMT --credit-cap 300 --execute
venv\Scripts\python.exe scripts\run_phantom_backfill_parallel.py --end-date 2026-08-20 --weekday 3 --years 0 --tickers CLX,ELV,FXI,GOOGL,HOOD,NKE,NOW,NVDA,NVS,OKE,PEP,STZ,T,TEM,WMT --credit-cap 300 --execute
