"""One-shot: append write_all_outputs_with_junior + _build_junior_section_cards to outputs file."""
import os, sys

TARGET = os.path.join(os.path.dirname(__file__), "pipeline_interpreter_outputs.py")

NEW_FUNCTIONS = (
    "\n\n"
    "def write_all_outputs_with_junior(\n"
    "    main_response: str,\n"
    "    story_response: str,\n"
    "    session,\n"
    "    run_dir,\n"
    "    ts: str,\n"
    "    ticker: str,\n"
    "    pre_trade_prob_block: str = \"\",\n"
    ") -> dict:\n"
    "    from pathlib import Path as _Path\n"
    "    results = {}\n"
    "    run_dir = _Path(run_dir)\n"
    "    run_dir.mkdir(parents=True, exist_ok=True)\n"
    "\n"
    "    (run_dir / f\"raw_response_{ts}.txt\").write_text(main_response, encoding=\"utf-8\")\n"
    "    (run_dir / f\"raw_story_{ts}.txt\").write_text(story_response, encoding=\"utf-8\")\n"
    "\n"
    "    brief_raw  = _extract_section(main_response, \"TRADE_BRIEF_CSV\")\n"
    "    brief_rows = _parse_csv(brief_raw) if brief_raw else []\n"
    "    for _row in brief_rows:\n"
    "        _t  = _row.get(\"ticker\", \"\")\n"
    "        _v  = _row.get(\"final_verdict\", \"WAIT\")\n"
    "        _st = _row.get(\"trade_state\", \"WATCH\")\n"
    "        if _t and hasattr(session, \"add_verdict\"):\n"
    "            session.add_verdict(_t, _v, _st)\n"
    "    session.last_ticker_csv = brief_rows\n"
    "\n"
    "    _BRIEF_FIELDS = [\n"
    "        \"ticker\", \"direction\", \"final_verdict\", \"trade_state\", \"horizon\", \"dte\",\n"
    "        \"trigger_level\", \"kill_switch_level\", \"preferred_contract\", \"premium\", \"rr\",\n"
    "        \"iv_context\", \"ivp\", \"earnings_in_window\", \"earnings_action\",\n"
    "        \"max_pain_risk\", \"sector_confirmation_required\", \"first_hour_rule\",\n"
    "        \"probe_permitted\", \"initial_adverse_tolerance\", \"capital_permission\",\n"
    "        \"narrative_summary\", \"execution_permission\",\n"
    "    ]\n"
    "    _bp = run_dir / f\"ticker_{ticker.lower()}_trade_brief_{ts}.csv\"\n"
    "    _write_csv(brief_rows, _bp, _BRIEF_FIELDS)\n"
    "    results[\"brief_csv\"] = {\"path\": _bp, \"rows\": len(brief_rows)}\n"
    "\n"
    "    main_html = build_html(main_response, session, ts, tickers=[ticker])\n"
    "\n"
    "    # PRE-TRADE PROBABILITY ASSESSMENT card\n"
    "    ete_block_html = \"\"\n"
    "    if pre_trade_prob_block:\n"
    "        _ete_esc = (\n"
    "            pre_trade_prob_block\n"
    "            .replace(\"&\", \"&amp;\")\n"
    "            .replace(\"<\", \"&lt;\")\n"
    "            .replace(\">\", \"&gt;\")\n"
    "        )\n"
    "        _card_hdr = (\n"
    "            \"<div style='background:#060f0c;border-bottom:1px solid #00d4aa44;\"\n"
    "            \"padding:14px 20px;display:flex;justify-content:space-between;\"\n"
    "            \"align-items:center'>\"\n"
    "            \"<div style='font-family:monospace;font-size:13px;\"\n"
    "            \"color:#00d4aa;font-weight:700;letter-spacing:2px'>\"\n"
    "            \"PRE-TRADE PROBABILITY ASSESSMENT</div>\"\n"
    "            \"<div style='font-size:10px;color:#4a5568;font-family:monospace'>\"\n"
    "            \"INFORMATIONAL ONLY &#8212; NEVER BLOCKS VERDICT</div>\"\n"
    "            \"</div>\"\n"
    "        )\n"
    "        _card_body = (\n"
    "            \"<div style='padding:20px 24px'>\"\n"
    "            \"<pre style='font-family:monospace;font-size:13px;color:#dde4f0;\"\n"
    "            \"background:#060810;border:1px solid #1c2235;border-radius:6px;\"\n"
    "            \"padding:16px 18px;overflow-x:auto;white-space:pre;line-height:1.6;\"\n"
    "            \"margin:0'>\" + _ete_esc + \"</pre></div>\"\n"
    "        )\n"
    "        ete_block_html = (\n"
    "            \"<div style='max-width:1280px;margin:0 auto;padding:0 40px 0'>\"\n"
    "            \"<div style='background:#0b0d16;border:2px solid #00d4aa44;\"\n"
    "            \"border-radius:8px;margin-top:24px;overflow:hidden'>\"\n"
    "            + _card_hdr + _card_body +\n"
    "            \"</div></div>\"\n"
    "        )\n"
    "\n"
    "    try:\n"
    "        junior_html = _build_junior_section_cards(story_response, ticker, ts)\n"
    "    except Exception:\n"
    "        junior_html = \"<p style='color:#4a5568;font-family:monospace'>Junior briefing unavailable.</p>\"\n"
    "\n"
    "    _jr_hdr = (\n"
    "        \"<div style='background:#060f0c;border-bottom:1px solid #00d4aa44;\"\n"
    "        \"padding:14px 20px;display:flex;justify-content:space-between;\"\n"
    "        \"align-items:center'>\"\n"
    "        \"<div style='font-family:monospace;font-size:13px;\"\n"
    "        \"color:#00d4aa;font-weight:700;letter-spacing:2px'>JUNIOR TRADER BRIEFING</div>\"\n"
    "        \"<div style='font-size:10px;color:#4a5568;font-family:monospace'>\"\n"
    "        \"EXECUTION PERMISSION: NONE &#8212; READ ONLY</div>\"\n"
    "        \"</div>\"\n"
    "    )\n"
    "    junior_block = (\n"
    "        \"<div style='max-width:1280px;margin:0 auto;padding:0 40px 40px'>\"\n"
    "        \"<div style='background:#0b0d16;border:2px solid #00d4aa44;\"\n"
    "        \"border-radius:8px;margin-top:24px;overflow:hidden'>\"\n"
    "        + _jr_hdr +\n"
    "        \"<div style='padding:20px 24px'>\" + junior_html + \"</div>\"\n"
    "        \"</div></div>\"\n"
    "    )\n"
    "\n"
    "    unified_html = main_html.replace(\"</body>\", ete_block_html + junior_block + \"\\n</body>\")\n"
    "\n"
    "    hp = run_dir / f\"ticker_{ticker.lower()}_interpreter_{ts}.html\"\n"
    "    hp.write_text(unified_html, encoding=\"utf-8\")\n"
    "    results[\"html\"] = {\"path\": hp}\n"
    "    print(f\"  \\u2705 Unified HTML: {hp.name}\")\n"
    "    return results\n"
    "\n"
    "\n"
    "def _build_junior_section_cards(story_response: str, ticker: str, ts: str) -> str:\n"
    "    pill_bar = \"<div style='display:flex;gap:6px;flex-wrap:wrap;margin:0 0 20px 0'>\"\n"
    "    for tag, num, label in _SECTION_LABELS:\n"
    "        em = \"\\u2014\"\n"
    "        short = label.split(em)[0].strip() if em in label else label.split(\"&\")[0].strip()\n"
    "        pill_bar += (\n"
    "            f\"<a href='#{tag}_jr' style='text-decoration:none;padding:5px 12px;\"\n"
    "            f\"border-radius:20px;background:#101420;border:1px solid #1c2235;\"\n"
    "            f\"font-size:11px;color:#8895b0;font-family:monospace'>{num} {short}</a>\"\n"
    "        )\n"
    "    pill_bar += \"</div>\"\n"
    "\n"
    "    cards_html = \"\"\n"
    "    for tag, num, label in _SECTION_LABELS:\n"
    "        content = _extract_junior_section(story_response, tag, ticker)\n"
    "        if not content:\n"
    "            content = \"Section not generated.\"\n"
    "        status = _extract_status(content)\n"
    "        badge  = _story_badge_html(status)\n"
    "        interdep_match = re.search(r\"INTERDEP:\\s*(.+?)(?:\\n|$)\", content, re.IGNORECASE | re.DOTALL)\n"
    "        interdep_html  = \"\"\n"
    "        if interdep_match:\n"
    "            interdep_text = interdep_match.group(1).strip()\n"
    "            content = content[:interdep_match.start()].strip()\n"
    "            interdep_html = (\n"
    "                f\"<div style='border-top:1px solid #1c2235;margin-top:16px;\"\n"
    "                f\"padding-top:10px;font-size:11px;color:#4a5568;font-family:monospace'>\"\n"
    "                f\"INTERDEP: {interdep_text}</div>\"\n"
    "            )\n"
    "        cards_html += (\n"
    "            f\"<div id='{tag}_jr' style='background:#060810;border:1px solid #1c2235;\"\n"
    "            f\"border-radius:8px;margin-bottom:14px;overflow:hidden'>\"\n"
    "            f\"<div style='padding:12px 16px;border-bottom:1px solid #1c2235;\"\n"
    "            f\"display:flex;justify-content:space-between;align-items:center'>\"\n"
    "            f\"<div style='font-family:monospace;font-size:12px;\"\n"
    "            f\"color:#dde4f0;font-weight:600'>{num}. {label}</div>\"\n"
    "            f\"{badge}</div>\"\n"
    "            f\"<div style='padding:14px 16px' class='narrative-content'>\"\n"
    "            f\"{_md_to_html(content)}\"\n"
    "            f\"{interdep_html}\"\n"
    "            f\"</div></div>\"\n"
    "        )\n"
    "    return pill_bar + cards_html\n"
)

# Parse to confirm it's valid Python before writing
import ast
try:
    ast.parse(NEW_FUNCTIONS)
    print("Syntax check: OK")
except SyntaxError as e:
    print(f"Syntax ERROR: {e}")
    sys.exit(1)

# Append to target file (raw bytes to avoid encoding issues)
with open(TARGET, "rb") as f:
    existing = f.read()

new_bytes = NEW_FUNCTIONS.encode("utf-8")
with open(TARGET, "wb") as f:
    f.write(existing + new_bytes)

print(f"Appended {len(new_bytes)} bytes to {os.path.basename(TARGET)}")
print("Done.")
