"""AVS-TST-DOI-001 / track T5 -- INDEPENDENT reference implementation.

WRITTEN BEFORE READING THE ENGINE. Do not edit this file after engine
inspection except to add fixtures; the arithmetic below is the audit's
own ground truth.

Model: Merton (1973) dividend-adjusted Black-Scholes, continuous dividend
yield q, i.e. the forward is priced off S*exp(-q*T).

    d1 = ( ln(S/K) + (r - q + 0.5*sigma^2)*T ) / (sigma*sqrt(T))
    d2 = d1 - sigma*sqrt(T)

    C = S*e^{-qT}*N(d1) - K*e^{-rT}*N(d2)
    P = K*e^{-rT}*N(-d2) - S*e^{-qT}*N(-d1)

    delta_C = e^{-qT}*N(d1)
    delta_P = -e^{-qT}*N(-d1)          ( = delta_C - e^{-qT} )
    gamma   = e^{-qT}*n(d1) / (S*sigma*sqrt(T))          (same both sides)
    vega    = S*e^{-qT}*n(d1)*sqrt(T)                    (same both sides)
              -- per 1.00 of vol (i.e. per 100 vol points). Divide by 100
                 for the "per 1 vol point" convention.
    theta_C = -S*e^{-qT}*n(d1)*sigma/(2*sqrt(T))
              + q*S*e^{-qT}*N(d1) - r*K*e^{-rT}*N(d2)     (per YEAR)
    theta_P = -S*e^{-qT}*n(d1)*sigma/(2*sqrt(T))
              - q*S*e^{-qT}*N(-d1) + r*K*e^{-rT}*N(-d2)   (per YEAR)
    rho_C   =  K*T*e^{-rT}*N(d2)
    rho_P   = -K*T*e^{-rT}*N(-d2)

Identities the audit will assert independently of the engine:
    (I1) put-call parity:   C - P = S*e^{-qT} - K*e^{-rT}
    (I2) delta_C - delta_P = e^{-qT}
    (I3) gamma_C == gamma_P, vega_C == vega_P
    (I4) sign(theta) -- negative for a long option when carry terms are
         small; the only legitimate positive-theta long cases are deep-ITM
         European puts (r*K*e^{-rT}*N(-d2) dominant) and deep-ITM European
         calls on a high-yield underlying.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, asdict

SQRT_2 = math.sqrt(2.0)
INV_SQRT_2PI = 1.0 / math.sqrt(2.0 * math.pi)


def norm_cdf(x: float) -> float:
    """Standard normal CDF via erfc (avoids catastrophic cancellation in the
    left tail, unlike 0.5*(1+erf(x/sqrt(2))))."""
    return 0.5 * math.erfc(-x / SQRT_2)


def norm_pdf(x: float) -> float:
    return INV_SQRT_2PI * math.exp(-0.5 * x * x)


@dataclass(frozen=True)
class RefGreeks:
    price: float
    delta: float
    gamma: float
    theta_year: float      # per year
    theta_day_365: float   # per calendar day
    theta_day_252: float   # per trading session
    vega_1pt: float        # per 1 vol point (0.01 of sigma)
    vega_full: float       # per 1.00 of sigma
    rho_1pt: float         # per 1 rate point (0.01 of r)
    d1: float
    d2: float

    def as_dict(self):
        return asdict(self)


def bs_merton(
    S: float,
    K: float,
    T: float,
    r: float,
    sigma: float,
    q: float = 0.0,
    right: str = "call",
) -> RefGreeks:
    """Dividend-adjusted (Merton) Black-Scholes. T in YEARS (calendar).

    Deliberately naive/explicit: this is audit arithmetic, not fast code.
    """
    right = right.lower()
    if right not in ("call", "put", "c", "p"):
        raise ValueError(f"right must be call/put, got {right!r}")
    is_call = right.startswith("c")

    if T <= 0.0:
        intrinsic = max(S - K, 0.0) if is_call else max(K - S, 0.0)
        return RefGreeks(intrinsic, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                         float("nan"), float("nan"))
    if sigma <= 0.0:
        raise ValueError("sigma must be > 0 for the reference model")

    sq = math.sqrt(T)
    vs = sigma * sq
    df_r = math.exp(-r * T)
    df_q = math.exp(-q * T)

    d1 = (math.log(S / K) + (r - q + 0.5 * sigma * sigma) * T) / vs
    d2 = d1 - vs

    nd1 = norm_cdf(d1)
    nd2 = norm_cdf(d2)
    n_md1 = norm_cdf(-d1)
    n_md2 = norm_cdf(-d2)
    pdf1 = norm_pdf(d1)

    if is_call:
        price = S * df_q * nd1 - K * df_r * nd2
        delta = df_q * nd1
        theta_year = (
            -(S * df_q * pdf1 * sigma) / (2.0 * sq)
            + q * S * df_q * nd1
            - r * K * df_r * nd2
        )
        rho_full = K * T * df_r * nd2
    else:
        price = K * df_r * n_md2 - S * df_q * n_md1
        delta = -df_q * n_md1
        theta_year = (
            -(S * df_q * pdf1 * sigma) / (2.0 * sq)
            - q * S * df_q * n_md1
            + r * K * df_r * n_md2
        )
        rho_full = -K * T * df_r * n_md2

    gamma = df_q * pdf1 / (S * vs)
    vega_full = S * df_q * pdf1 * sq

    return RefGreeks(
        price=price,
        delta=delta,
        gamma=gamma,
        theta_year=theta_year,
        theta_day_365=theta_year / 365.0,
        theta_day_252=theta_year / 252.0,
        vega_1pt=vega_full / 100.0,
        vega_full=vega_full,
        rho_1pt=rho_full / 100.0,
        d1=d1,
        d2=d2,
    )


# ---------------------------------------------------------------------------
# Independent cross-checks that do not use the closed form at all.
# ---------------------------------------------------------------------------

def bs_price_only(S, K, T, r, sigma, q, right) -> float:
    return bs_merton(S, K, T, r, sigma, q, right).price


def fd_delta(S, K, T, r, sigma, q, right, h=None) -> float:
    h = h or S * 1e-5
    up = bs_price_only(S + h, K, T, r, sigma, q, right)
    dn = bs_price_only(S - h, K, T, r, sigma, q, right)
    return (up - dn) / (2.0 * h)


def fd_gamma(S, K, T, r, sigma, q, right, h=None) -> float:
    h = h or S * 1e-4
    up = bs_price_only(S + h, K, T, r, sigma, q, right)
    mid = bs_price_only(S, K, T, r, sigma, q, right)
    dn = bs_price_only(S - h, K, T, r, sigma, q, right)
    return (up - 2.0 * mid + dn) / (h * h)


def fd_vega_full(S, K, T, r, sigma, q, right, h=1e-5) -> float:
    up = bs_price_only(S, K, T, r, sigma + h, q, right)
    dn = bs_price_only(S, K, T, r, sigma - h, q, right)
    return (up - dn) / (2.0 * h)


def fd_theta_year(S, K, T, r, sigma, q, right, h=1e-6) -> float:
    """dV/dt = -dV/dT."""
    up = bs_price_only(S, K, T + h, r, sigma, q, right)
    dn = bs_price_only(S, K, T - h, r, sigma, q, right)
    return -(up - dn) / (2.0 * h)


def binomial_american(S, K, T, r, sigma, q, right, steps=3000) -> float:
    """CRR binomial, American exercise. Used ONLY to size the American
    premium the spec (SS11.4) says must be disclosed for deep-ITM puts."""
    is_call = right.lower().startswith("c")
    dt = T / steps
    u = math.exp(sigma * math.sqrt(dt))
    d = 1.0 / u
    disc = math.exp(-r * dt)
    p = (math.exp((r - q) * dt) - d) / (u - d)
    if not (0.0 < p < 1.0):
        raise ValueError("binomial p out of range; reduce steps or dt")
    # terminal layer
    vals = []
    for i in range(steps + 1):
        ST = S * (u ** (steps - i)) * (d ** i)
        vals.append(max(ST - K, 0.0) if is_call else max(K - ST, 0.0))
    for step in range(steps - 1, -1, -1):
        for i in range(step + 1):
            cont = disc * (p * vals[i] + (1.0 - p) * vals[i + 1])
            ST = S * (u ** (step - i)) * (d ** i)
            exer = max(ST - K, 0.0) if is_call else max(K - ST, 0.0)
            vals[i] = cont if cont > exer else exer
        vals = vals[: step + 1]
    return vals[0]


def binomial_european(S, K, T, r, sigma, q, right, steps=3000) -> float:
    is_call = right.lower().startswith("c")
    dt = T / steps
    u = math.exp(sigma * math.sqrt(dt))
    d = 1.0 / u
    disc = math.exp(-r * dt)
    p = (math.exp((r - q) * dt) - d) / (u - d)
    vals = []
    for i in range(steps + 1):
        ST = S * (u ** (steps - i)) * (d ** i)
        vals.append(max(ST - K, 0.0) if is_call else max(K - ST, 0.0))
    for step in range(steps - 1, -1, -1):
        for i in range(step + 1):
            vals[i] = disc * (p * vals[i] + (1.0 - p) * vals[i + 1])
        vals = vals[: step + 1]
    return vals[0]


# ---------------------------------------------------------------------------
# The six-plus audit fixtures. Frozen here BEFORE engine inspection.
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Fixture:
    fid: str
    label: str
    S: float
    K: float
    T: float          # calendar years to expiry
    dte_cal: int      # calendar days to expiry (T = dte_cal/365)
    r: float
    sigma: float
    q: float
    right: str


FIXTURES = [
    Fixture("T5-F1", "ATM CALL, short DTE (30d), no div",
            S=100.0, K=100.0, T=30 / 365, dte_cal=30, r=0.045, sigma=0.28, q=0.0, right="call"),
    Fixture("T5-F2", "OTM CALL, short DTE (21d), dividend payer",
            S=100.0, K=110.0, T=21 / 365, dte_cal=21, r=0.045, sigma=0.32, q=0.02, right="call"),
    Fixture("T5-F3", "ITM CALL, long DTE (365d), dividend payer",
            S=120.0, K=100.0, T=365 / 365, dte_cal=365, r=0.045, sigma=0.25, q=0.03, right="call"),
    Fixture("T5-F4", "ATM PUT, short DTE (30d), no div",
            S=100.0, K=100.0, T=30 / 365, dte_cal=30, r=0.045, sigma=0.28, q=0.0, right="put"),
    Fixture("T5-F5", "OTM PUT, long DTE (180d), dividend payer",
            S=100.0, K=85.0, T=180 / 365, dte_cal=180, r=0.045, sigma=0.30, q=0.02, right="put"),
    Fixture("T5-F6", "DEEP-ITM PUT, long DTE (270d) -- AMERICAN EXERCISE CASE",
            S=60.0, K=100.0, T=270 / 365, dte_cal=270, r=0.05, sigma=0.22, q=0.0, right="put"),
    # parity partners (same K/T/r/sigma/q as F3/F6) so C-P parity is testable
    Fixture("T5-F7", "ITM CALL parity partner of F3 -> PUT leg",
            S=120.0, K=100.0, T=365 / 365, dte_cal=365, r=0.045, sigma=0.25, q=0.03, right="put"),
    Fixture("T5-F8", "DEEP-OTM CALL parity partner of F6",
            S=60.0, K=100.0, T=270 / 365, dte_cal=270, r=0.05, sigma=0.22, q=0.0, right="call"),
]


def fixture_table():
    rows = []
    for f in FIXTURES:
        g = bs_merton(f.S, f.K, f.T, f.r, f.sigma, f.q, f.right)
        rows.append((f, g))
    return rows


if __name__ == "__main__":
    import json
    out = []
    for f, g in fixture_table():
        d = {"fid": f.fid, "label": f.label, "right": f.right,
             "S": f.S, "K": f.K, "T": f.T, "r": f.r, "sigma": f.sigma, "q": f.q}
        d.update(g.as_dict())
        out.append(d)
    print(json.dumps(out, indent=2))
